//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Tomori.Epartner.Data.Model;
using Vleko.Result;
using Tomori.Epartner.Core.Response;

namespace Tomori.Epartner.Core.VendorLandasanHukum.Query
{

    public class GetVendorLandasanHukumByIdRequest : IRequest<ObjectResponse<VendorLandasanHukumResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetVendorLandasanHukumByIdHandler : IRequestHandler<GetVendorLandasanHukumByIdRequest, ObjectResponse<VendorLandasanHukumResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetVendorLandasanHukumByIdHandler(
            ILogger<GetVendorLandasanHukumByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<VendorLandasanHukumResponse>> Handle(GetVendorLandasanHukumByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<VendorLandasanHukumResponse> result = new ObjectResponse<VendorLandasanHukumResponse>();
            try
            {
                var item = await _context.Entity<Tomori.Epartner.Data.Model.VendorLandasanHukum>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<VendorLandasanHukumResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id Tomori.Epartner.Data.Model.VendorLandasanHukum {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail VendorLandasanHukum", request.Id);
                result.Error("Failed Get Detail VendorLandasanHukum", ex.Message);
            }
            return result;
        }
    }
}

