//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Tomori.Epartner.Data.Model;
using Vleko.Result;
using Tomori.Epartner.Core.Response;

namespace Tomori.Epartner.Core.VendorBranch.Query
{

    public class GetVendorBranchByIdRequest : IRequest<ObjectResponse<VendorBranchResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetVendorBranchByIdHandler : IRequestHandler<GetVendorBranchByIdRequest, ObjectResponse<VendorBranchResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetVendorBranchByIdHandler(
            ILogger<GetVendorBranchByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<VendorBranchResponse>> Handle(GetVendorBranchByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<VendorBranchResponse> result = new ObjectResponse<VendorBranchResponse>();
            try
            {
                var item = await _context.Entity<Tomori.Epartner.Data.Model.VendorBranch>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<VendorBranchResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id Tomori.Epartner.Data.Model.VendorBranch {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail VendorBranch", request.Id);
                result.Error("Failed Get Detail VendorBranch", ex.Message);
            }
            return result;
        }
    }
}

