//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Tomori.Epartner.Data.Model;
using Vleko.Result;
using Tomori.Epartner.Core.Response;
using Tomori.Epartner.Core.Helper;

namespace Tomori.Epartner.Core.VendorBranch.Query
{
    public class GetVendorBranchListRequest : ListRequest,IListRequest<GetVendorBranchListRequest>,IRequest<ListResponse<VendorBranchResponse>>
    {
    }
    internal class GetVendorBranchListHandler : IRequestHandler<GetVendorBranchListRequest, ListResponse<VendorBranchResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetVendorBranchListHandler(
            ILogger<GetVendorBranchListHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }

        public async Task<ListResponse<VendorBranchResponse>> Handle(GetVendorBranchListRequest request, CancellationToken cancellationToken)
        {
            ListResponse<VendorBranchResponse> result = new ListResponse<VendorBranchResponse>();
            try
            {
				var query = _context.Entity<Tomori.Epartner.Data.Model.VendorBranch>().AsQueryable();

				#region Filter
				Expression<Func<Tomori.Epartner.Data.Model.VendorBranch, object>> column_sort = null;
				List<Expression<Func<Tomori.Epartner.Data.Model.VendorBranch, bool>>> where = new List<Expression<Func<Tomori.Epartner.Data.Model.VendorBranch, bool>>>();
				if (request.Filter != null && request.Filter.Count > 0)
				{
					foreach (var f in request.Filter)
					{
						var obj = ListExpression(f.Search, f.Field, true);
						if (obj.where != null)
							where.Add(obj.where);
					}
				}
				if (where != null && where.Count() > 0)
				{
					foreach (var w in where)
					{
						query = query.Where(w);
					}
				}
				if (request.Sort != null)
                {
					column_sort = ListExpression(request.Sort.Field, request.Sort.Field, false).order!;
					if(column_sort != null)
						query = request.Sort.Type == SortTypeEnum.ASC ? query.OrderBy(column_sort) : query.OrderByDescending(column_sort);
					else
						query = query.OrderBy(d=>d.Id);
				}
				#endregion

				var query_count = query;
				if (request.Start.HasValue && request.Length.HasValue && request.Length > 0)
					query = query.Skip((request.Start.Value - 1) * request.Length.Value).Take(request.Length.Value);
				var data_list = await query.ToListAsync();

				result.List = _mapper.Map<List<VendorBranchResponse>>(data_list);
				result.Filtered = data_list.Count();
				result.Count = await query_count.CountAsync();
				result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get List VendorBranch", request);
                result.Error("Failed Get List VendorBranch", ex.Message);
            }
            return result;
        }

        #region List Utility
		private (Expression<Func<Tomori.Epartner.Data.Model.VendorBranch, bool>> where, Expression<Func<Tomori.Epartner.Data.Model.VendorBranch, object>> order) ListExpression(string search, string field, bool is_where)
		{
			Expression<Func<Tomori.Epartner.Data.Model.VendorBranch, object>> result_order = null;
			Expression<Func<Tomori.Epartner.Data.Model.VendorBranch, bool>> result_where = null;
            if (!string.IsNullOrWhiteSpace(search) && !string.IsNullOrWhiteSpace(field))
            {
                field = field.Trim().ToLower();
                search = search.Trim().ToLower();
                switch (field)
                {
					case "id" : 
						if(is_where){
							if (Guid.TryParse(search, out var _Id))
								result_where = (d=>d.Id == _Id);
								else
								result_where = (d=>d.Id == Guid.Empty);
						}
						else
							result_order = (d => d.Id);
					break;
					case "address" : 
						if(is_where){
							result_where = (d=>d.Address.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Address);
					break;
					case "civdid" : 
						if(is_where){
							if (int.TryParse(search, out var _CivdId))
								result_where = (d=>d.CivdId == _CivdId);
						}
						else
							result_order = (d => d.CivdId);
					break;
					case "companytype" : 
						if(is_where){
							result_where = (d=>d.CompanyType.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.CompanyType);
					break;
					case "completeddate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _CompletedDate))
								result_where = (d=>d.CompletedDate == _CompletedDate);
						}
						else
							result_order = (d => d.CompletedDate);
					break;
					case "contactperson" : 
						if(is_where){
							result_where = (d=>d.ContactPerson.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.ContactPerson);
					break;
					case "createby" : 
						if(is_where){
							result_where = (d=>d.CreateBy.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.CreateBy);
					break;
					case "createdate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _CreateDate))
								result_where = (d=>d.CreateDate == _CreateDate);
						}
						else
							result_order = (d => d.CreateDate);
					break;
					case "faxnumber" : 
						if(is_where){
							result_where = (d=>d.FaxNumber.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.FaxNumber);
					break;
					case "idvendor" : 
						if(is_where){
							if (Guid.TryParse(search, out var _IdVendor))
								result_where = (d=>d.IdVendor == _IdVendor);
								else
								result_where = (d=>d.IdVendor == Guid.Empty);
						}
						else
							result_order = (d => d.IdVendor);
					break;
					case "npwp" : 
						if(is_where){
							result_where = (d=>d.Npwp.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Npwp);
					break;
					case "phonenumber" : 
						if(is_where){
							result_where = (d=>d.PhoneNumber.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.PhoneNumber);
					break;
					case "pkp" : 
						if(is_where){
							result_where = (d=>d.Pkp.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Pkp);
					break;
					case "situ" : 
						if(is_where){
							result_where = (d=>d.Situ.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Situ);
					break;
					case "updateby" : 
						if(is_where){
							result_where = (d=>d.UpdateBy.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.UpdateBy);
					break;
					case "updatedate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _UpdateDate))
								result_where = (d=>d.UpdateDate == _UpdateDate);
						}
						else
							result_order = (d => d.UpdateDate);
					break;
					case "vendorbranchname" : 
						if(is_where){
							result_where = (d=>d.VendorBranchName.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.VendorBranchName);
					break;
					case "vendoremail1" : 
						if(is_where){
							result_where = (d=>d.VendorEmail1.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.VendorEmail1);
					break;
					case "vendoremail2" : 
						if(is_where){
							result_where = (d=>d.VendorEmail2.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.VendorEmail2);
					break;
					case "zipcode" : 
						if(is_where){
							result_where = (d=>d.ZipCode.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.ZipCode);
					break;

                }
            }
            return (result_where, result_order);
        }
        #endregion
    }
}

