//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Tomori.Epartner.Core.Request
{
    public partial class WorkflowConfigDetailRequest
    {
		public DateTime? AutoApproveExpired{ get; set; }
		[Required]
		public bool CanAdhoc{ get; set; }
		[Required]
		public Guid IdUser{ get; set; }
		[Required]
		public Guid IdWorkflowConfig{ get; set; }
		[Required]
		public bool IsReviewer{ get; set; }
		[Required]
		public string StepName{ get; set; }
		[Required]
		public int StepNo{ get; set; }

    }
}

