//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Vleko.Result;
using Tomori.Epartner.Core.Helper;
using Tomori.Epartner.Core.Request;
//using Tomori.Epartner.Core.Log.Command;
using Microsoft.Extensions.Caching.Memory;
using Tomori.Epartner.Core.Attributes;
using Tomori.Epartner.Core.Config.Query;
using DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Wordprocessing;
using Tomori.Epartner.Data.Model;

namespace Tomori.Epartner.Core.Config.Command
{
    #region Request
    public class SaveConfigMailMapping : Profile
    {
        public SaveConfigMailMapping()
        {
            CreateMap<SaveConfigMailRequest, EmailConfig>().ReverseMap();
        }
    }
    public class SaveConfigMailRequest : EmailConfig, IRequest<StatusResponse>
    {
        [Required]
        public TokenUserObject Token { get; set; }
    }
    #endregion

    internal class SaveConfigMailHandler : IRequestHandler<SaveConfigMailRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;
        private readonly IMemoryCache _cache;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public SaveConfigMailHandler(
            ILogger<SaveConfigMailHandler> logger,
            IMapper mapper,
            IMediator mediator,
            IMemoryCache cache,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _mediator = mediator;
            _cache = cache;
            _context = context;
        }
        public async Task<StatusResponse> Handle(SaveConfigMailRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                var data_list = await _context.Entity<Data.Model.Config>().Where(d => d.Category == ConfigCategory.EMAIL.ToString()).ToListAsync();

                var Password = data_list.FirstOrDefault(d => d.Id == "MAIL_PWD");
                var SenderMail = data_list.FirstOrDefault(d => d.Id == "MAIL_SEND");
                var Smtp = data_list.FirstOrDefault(d => d.Id == "MAIL_SMTP");
                var SmtpPort = data_list.FirstOrDefault(d => d.Id == "MAIL_PORT");

                if (SetValue(ref Password, request.Password, request.Token))
                    _context.Update(Password);
                if (SetValue(ref SenderMail, request.SenderMail, request.Token))
                    _context.Update(SenderMail);
                if (SetValue(ref Smtp, request.Smtp, request.Token))
                    _context.Update(Smtp);
                if (SetValue(ref SmtpPort, request.SmtpPort.ToString(), request.Token))
                    _context.Update(SmtpPort);

                var save = await _context.Commit();
                if (save.Success)
                {
                    _cache.Remove($"{CacheKey.CONFIG}_{ConfigCategory.EMAIL.ToString()}");
                    //_ = Task.Run(() => _mediator.Send(new AddChangeLogRequest() { IdUser = request.Token.Id, ChangeLog = save.log }));
                    result.OK();
                }
                else
                    result.BadRequest(save.Message);

                return result;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Save Config Email", request);
                result.Error("Failed Save Config Email", ex.Message);
            }
            return result;
        }
        private bool SetValue(ref Data.Model.Config config, string value, TokenUserObject token)
        {
            if (config.Value != value)
            {
                config.Value = value;
                config.UpdateDate = DateTime.Now;
                config.UpdateBy = token.Username;
                return true;
            }
            else
                return false;
        }
    }
}

