//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Vleko.Result;
using Tomori.Epartner.Core.Helper;
using Tomori.Epartner.Core.Request;
//using Tomori.Epartner.Core.Log.Command;
using Microsoft.Extensions.Caching.Memory;
using Tomori.Epartner.Core.Attributes;

namespace Tomori.Epartner.Core.Identity.Page.Command
{

    #region Request
    public class AddPageMapping: Profile
    {
        public AddPageMapping()
        {
            CreateMap<AddPageRequest, PageRequest>().ReverseMap();
        }
    }
    public class AddPageRequest :PageRequest, IMapRequest<Tomori.Epartner.Data.Model.Page, AddPageRequest>,IRequest<StatusResponse>
    {
        [Required]
        public TokenUserObject Token { get; set; }
        public void Mapping(IMappingExpression<AddPageRequest, Tomori.Epartner.Data.Model.Page> map)
        {
            //use this for mapping
            //map.ForMember(d => d.EF_COLUMN, opt => opt.MapFrom(s => s.Object));
        }
    }
    #endregion

    internal class AddPageHandler : IRequestHandler<AddPageRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMemoryCache _cache;
        private readonly IMediator _mediator;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public AddPageHandler(
            ILogger<AddPageHandler> logger,
            IMapper mapper,
            IMemoryCache cache,
            IMediator mediator,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _cache = cache;
            _mediator = mediator;
            _context = context;
        }
        public async Task<StatusResponse> Handle(AddPageRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                var data = _mapper.Map<Tomori.Epartner.Data.Model.Page>(request);
                data.Id = Guid.NewGuid();
                data.CreateBy = request.Token.Username;
                data.CreateDate = DateTime.Now;
                _context.Add(data);

                if (data.Navigation != "#")
                {
                    _context.Add(new Data.Model.PagePermission
                    {
                        Id = Guid.NewGuid(),
                        IdPage = data.Id,
                        Name = ".view",
                        Active = true,
                        CreateBy = request.Token.Username,
                        CreateDate = DateTime.Now
                    });
                }

                var add = await _context.Commit();
                if (add.Success)
                {
                    _cache.Remove(CacheKey.PAGE);
                    _cache.Remove(CacheKey.PAGE_PERMISSION);
                    //_ = Task.Run(() => _mediator.Send(new AddChangeLogRequest() { IdUser = request.Token.Id, ChangeLog = add.log }));
                    result.OK();
                }
                else
                    result.BadRequest(add.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Add Page", request);
                result.Error("Failed Add Page", ex.Message);
            }
            return result;
        }
    }
}

