//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using Tomori.Epartner.Core.Attributes;
using System.ComponentModel.DataAnnotations;

namespace Tomori.Epartner.Core.Request
{
    public partial class ConfigRequest
    {
		[Required]
		public string Id{ get; set; }
		[Required]
		public ConfigCategory Category { get; set; }
		[Required]
		public string Name{ get; set; }
		[Required]
		public string Value{ get; set; }

    }
}

