//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using Tomori.Epartner.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Tomori.Epartner.Data.Model;
using Tomori.Epartner.Core.Attributes;

namespace Tomori.Epartner.Core.Response
{
    public partial class ConfigResponse : IMapResponse<ConfigResponse, Tomori.Epartner.Data.Model.Config>
    {
        public string Id { get; set; }
        public ConfigCategory Category { get; set; }
        public string Name { get; set; }
        public string CreateBy { get; set; }
        public DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string Value { get; set; }


        public void Mapping(IMappingExpression<Tomori.Epartner.Data.Model.Config, ConfigResponse> map)
        {
            //use this for mapping
            map.ForMember(d => d.Category, opt => opt.MapFrom(s => Enum.Parse(typeof(ConfigCategory), s.Category, true)));
        }
    }
}

