//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Tomori.Epartner.Data.Model;
using Vleko.Result;
using Tomori.Epartner.Core.Response;
using Tomori.Epartner.Core.Helper;
using Microsoft.Extensions.Caching.Memory;
using Tomori.Epartner.Core.Attributes;
using System.ComponentModel.DataAnnotations;

namespace Tomori.Epartner.Core.ChangeConfig.Query
{
    public class GetModulChangeConfigRequest : IRequest<ListResponse<string>>
    {
    }
    internal class GetModulChangeConfigHandler : IRequestHandler<GetModulChangeConfigRequest, ListResponse<string>>
    {
        private readonly ILogger _logger;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetModulChangeConfigHandler(
            ILogger<GetModulChangeConfigHandler> logger,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _context = context;
        }

        public async Task<ListResponse<string>> Handle(GetModulChangeConfigRequest request, CancellationToken cancellationToken)
        {
            ListResponse<string> result = new ListResponse<string>();
            try
            {
                result.List = await _context.Entity<Data.Model.ChangeConfig>().GroupBy(d => d.Modul).Select(d=>d.Key).ToListAsync();

                result.Count = result.List.Count;
                result.Filtered = result.List.Count;
                result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get List Modul ChangeConfig", request);
                result.Error("Failed Get List Modul ChangeConfig", ex.Message);
            }
            return result;
        }
    }
}

