//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Tomori.Epartner.Data.Model;
using Vleko.Result;
using Tomori.Epartner.Core.Response;
using Tomori.Epartner.Core.Helper;
using Microsoft.Extensions.Caching.Memory;
using Tomori.Epartner.Core.Attributes;

namespace Tomori.Epartner.Core.Identity.Page.Query
{
    public class GetPageRequest : IRequest<ListResponse<PageResponse>>
    {
		public string Search { get; set; }
		public int? Start { get; set; }
		public int? Length { get; set; }
    }
    internal class GetPageHandler : IRequestHandler<GetPageRequest, ListResponse<PageResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMemoryCache _cache;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetPageHandler(
            ILogger<GetPageHandler> logger,
            IMapper mapper,
            IMemoryCache cache,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _cache = cache;
            _context = context;
        }

        public async Task<ListResponse<PageResponse>> Handle(GetPageRequest request, CancellationToken cancellationToken)
        {
            ListResponse<PageResponse> result = new ListResponse<PageResponse>();
            try
            {
                if (_cache.TryGetValue(CacheKey.PAGE, out IEnumerable<PageResponse> data))
                {
                    result.List = data.ToList();
                }
                else
                {
                    var data_list = await _context.Entity<Tomori.Epartner.Data.Model.Page>().Where(d=>!d.IdParent.HasValue).Include(d=>d.InverseIdParentNavigation).ToListAsync();
				    result.List = _mapper.Map<List<PageResponse>>(data_list);
                    var cacheEntryOptions = new MemoryCacheEntryOptions()
                               .SetSlidingExpiration(TimeSpan.FromSeconds(60))
                               .SetAbsoluteExpiration(TimeSpan.FromSeconds(3600))
                               .SetPriority(CacheItemPriority.Normal)
                               .SetSize(1024);

                    _cache.Set(CacheKey.PAGE, result.List, cacheEntryOptions);
                }
                if (result.List.Count() == 0)
                {
                    result.NotFound("Page Not Found!");
                    return result;
                }

                if (!string.IsNullOrWhiteSpace(request.Search))
                    result.List = result.List.Where(d => d.Name.Trim().ToLower().Contains(request.Search.Trim().ToLower())).ToList();

                result.List = result.List.OrderBy(d => d.Sort).ToList();

                result.Count = result.List.Count;
                if (request.Start.HasValue && request.Length.HasValue && request.Length > 0)
                    result.List = result.List.Skip((request.Start.Value - 1) * request.Length.Value).Take(request.Length.Value).ToList();

                result.Filtered = result.List.Count;
                result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get List Page", request);
                result.Error("Failed Get List Page", ex.Message);
            }
            return result;
        }
    }
}

