//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Vleko.Result;
using Tomori.Epartner.Core.Helper;
using Tomori.Epartner.Core.Request;
using Tomori.Epartner.Core.Log.Command;
using Microsoft.Extensions.Caching.Memory;
using Tomori.Epartner.Core.Attributes;

namespace Tomori.Epartner.Core.PdfTemplate.Command
{

    #region Request
    public class AddPdfTemplateMapping : Profile
    {
        public AddPdfTemplateMapping()
        {
            CreateMap<AddPdfTemplateRequest, PdfTemplateRequest>().ReverseMap();
        }
    }
    public class AddPdfTemplateRequest : PdfTemplateRequest, IMapRequest<Tomori.Epartner.Data.Model.DocumentTemplate, AddPdfTemplateRequest>,IRequest<StatusResponse>
    {
        [Required]
        public TokenUserObject Token { get; set; }
        public void Mapping(IMappingExpression<AddPdfTemplateRequest, Tomori.Epartner.Data.Model.DocumentTemplate> map)
        {
            //use this for mapping
            //map.ForMember(d => d.EF_COLUMN, opt => opt.MapFrom(s => s.Object));
        }
    }
    #endregion

    internal class AddPdfTemplateHandler : IRequestHandler<AddPdfTemplateRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMemoryCache _cache;
        private readonly IMediator _mediator;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public AddPdfTemplateHandler(
            ILogger<AddPdfTemplateHandler> logger,
            IMapper mapper,
            IMemoryCache cache,
            IMediator mediator,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _cache = cache;
            _mediator = mediator;
            _context = context;
        }
        public async Task<StatusResponse> Handle(AddPdfTemplateRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                var data = _mapper.Map<Tomori.Epartner.Data.Model.DocumentTemplate>(request);
                data.CreateBy = request.Token.Username;
                data.CreateDate = DateTime.Now;
                var add = await _context.AddSave(data);
                if (add.Success)
                {
                    _cache.Remove($"{CacheKey.PDF_TEMPLATE}_{data.Code}");
                    _ = Task.Run(() => _mediator.Send(new AddChangeLogRequest() { IdUser = request.Token.Id, ChangeLog = add.log }));
                    result.OK();
                }
                else
                    result.BadRequest(add.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Add DocumentTemplate", request);
                result.Error("Failed Add DocumentTemplate", ex.Message);
            }
            return result;
        }
    }
}

