//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using Vleko.Result;
using Tomori.Epartner.Core.Notification.Query;
using Tomori.Epartner.Core.Request;
using Tomori.Epartner.Core.Notification.Command;

namespace Tomori.Epartner.API.Controllers
{
    public partial class NotificationController : BaseController<NotificationController>
    {
        [HttpGet(template: "get/{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            return Wrapper(await _mediator.Send(new GetNotificationByIdRequest() { Id = id }), new { id });
        }

        [HttpGet(template: "count/{id_user}/{is_open}")]
        public async Task<IActionResult> GetCount(Guid id_user, bool is_open)
        {
            return Wrapper(await _mediator.Send(new GetNotificationCountRequest
            {
                IdUser = id_user,
                IsOpen = is_open
            }), new { id_user, is_open });
        }

        [HttpPost(template: "list")]
        public async Task<IActionResult> List([FromBody] ListRequest request)
        {
            var list_request = _mapper.Map<GetNotificationListRequest>(request);
            return Wrapper(await _mediator.Send(list_request), request);
        }

        [HttpPost(template: "add")]
        public async Task<IActionResult> Add([FromBody] NotificationRequest request)
        {
            var add_request = _mapper.Map<AddNotificationRequest>(request);
            add_request.Token = Token.User;
            return Wrapper(await _mediator.Send(add_request), request);
        }

        [HttpPut(template: "open/{id}")]
        public async Task<IActionResult> Open(Guid id)
        {
            return Wrapper(await _mediator.Send(new OpenNotificatioRequest() { Id = id }), new { id });
        }
        [HttpDelete(template: "delete/{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            return Wrapper(await _mediator.Send(new DeleteNotificationRequest() { Id = id, Token = Token.User }), new { id });
        }


    }
}

