//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using Tomori.Epartner.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Tomori.Epartner.Data.Model;

namespace Tomori.Epartner.Core.Response
{
    public partial class VendorSpdaResponse: IMapResponse<VendorSpdaResponse, Tomori.Epartner.Data.Model.VendorSpda>
    {
		public Guid Id{ get; set; }
		public int CivdId{ get; set; }
		public string CreateBy{ get; set; }
		public DateTime CreateDate{ get; set; }
		public DateTime? ExpiredDate{ get; set; }
		public string FileSpda{ get; set; }
		public string FileSpdaId{ get; set; }
		public Guid? IdVendor{ get; set; }
		public string SpdaNo{ get; set; }
		public string SpdaValidity{ get; set; }
		public string UpdateBy{ get; set; }
		public DateTime? UpdateDate{ get; set; }
		public DateTime? UploadDate{ get; set; }


        public void Mapping(IMappingExpression<Tomori.Epartner.Data.Model.VendorSpda, VendorSpdaResponse> map)
        {
            //use this for mapping
            //map.ForMember(d => d.object, opt => opt.MapFrom(s => s.EF_COLUMN));

        }
    }
}

