//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using Tomori.Epartner.Core.Attributes;
using System.ComponentModel.DataAnnotations;

namespace Tomori.Epartner.Core.Request
{
    public partial class DocumentTemplateRequest
    {
        [Required]
        public FileObject File { get; set; }
        [Required]
        public string Code { get; set; }
        public string Description { get; set; }

    }
}

