//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Tomori.Epartner.Data.Model;
using Vleko.Result;
using Tomori.Epartner.Core.Response;
using Tomori.Epartner.Core.Helper;
using Tomori.Epartner.Core.General.FaqQuestionnaire.Object;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Tomori.Epartner.Core.FaqQuestionnaire.Query
{
    public class GetFaqQuestionnaireListRequest : ListRequest,IListRequest<GetFaqQuestionnaireListRequest>,IRequest<ListResponse<FaqQuestionnaireGroupedResponse>>
    {
    }
    internal class GetFaqQuestionnaireListHandler : IRequestHandler<GetFaqQuestionnaireListRequest, ListResponse<FaqQuestionnaireGroupedResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetFaqQuestionnaireListHandler(
            ILogger<GetFaqQuestionnaireListHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }

        public async Task<ListResponse<FaqQuestionnaireGroupedResponse>> Handle(GetFaqQuestionnaireListRequest request, CancellationToken cancellationToken)
        {
            ListResponse<FaqQuestionnaireGroupedResponse> result = new ListResponse<FaqQuestionnaireGroupedResponse>();
            try
            {
				var query = _context.Entity<Tomori.Epartner.Data.Model.FaqQuestionnaire>().AsQueryable();

				#region Filter
				Expression<Func<Tomori.Epartner.Data.Model.FaqQuestionnaire, object>> column_sort = null;
				List<Expression<Func<Tomori.Epartner.Data.Model.FaqQuestionnaire, bool>>> where = new List<Expression<Func<Tomori.Epartner.Data.Model.FaqQuestionnaire, bool>>>();
				if (request.Filter != null && request.Filter.Count > 0)
				{
					foreach (var f in request.Filter)
					{
						var obj = ListExpression(f.Search, f.Field, true);
						if (obj.where != null)
							where.Add(obj.where);
					}
				}
				if (where != null && where.Count() > 0)
				{
					foreach (var w in where)
					{
						query = query.Where(w);
					}
				}
				if (request.Sort != null)
                {
					column_sort = ListExpression(request.Sort.Field, request.Sort.Field, false).order!;
					if(column_sort != null)
						query = request.Sort.Type == SortTypeEnum.ASC ? query.OrderBy(column_sort) : query.OrderByDescending(column_sort);
					else
						query = query.OrderBy(d=>d.Id);
				}
				#endregion

				var query_count = query;
				if (request.Start.HasValue && request.Length.HasValue && request.Length > 0)
					query = query.Skip((request.Start.Value - 1) * request.Length.Value).Take(request.Length.Value);
				var data_list = await query.ToListAsync();

				var data_questionare_listed = data_list.GroupBy(x => x.Section).Select(s => new FaqQuestionnaireGroupedResponse { 
					Section = s.Key,
					SectionValues = data_list.Where(w => w.Section == s.Key).Select(ss => new FaqSectionValue { 
						Id = ss.Id,
						Answer = ss.Answer,
						Question = ss.Questionnaire
					}).ToList()
				}).ToList();




				result.List = data_questionare_listed;

                result.Filtered = data_list.Count();
				result.Count = await query_count.CountAsync();
				result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get List FaqQuestionnaire", request);
                result.Error("Failed Get List FaqQuestionnaire", ex.Message);
            }
            return result;
        }

		private FaqSectionValue SetSecionValue(Data.Model.FaqQuestionnaire questi_list , string section)
		{
			return new FaqSectionValue
			{
				Answer = questi_list.Answer,
				Question = questi_list.Questionnaire
			};

        }

        #region List Utility
        private (Expression<Func<Tomori.Epartner.Data.Model.FaqQuestionnaire, bool>> where, Expression<Func<Tomori.Epartner.Data.Model.FaqQuestionnaire, object>> order) ListExpression(string search, string field, bool is_where)
		{
			Expression<Func<Tomori.Epartner.Data.Model.FaqQuestionnaire, object>> result_order = null;
			Expression<Func<Tomori.Epartner.Data.Model.FaqQuestionnaire, bool>> result_where = null;
            if (!string.IsNullOrWhiteSpace(search) && !string.IsNullOrWhiteSpace(field))
            {
                field = field.Trim().ToLower();
                search = search.Trim().ToLower();
                switch (field)
                {
					case "id" : 
						if(is_where){
							if (Guid.TryParse(search, out var _Id))
								result_where = (d=>d.Id == _Id);
								else
								result_where = (d=>d.Id == Guid.Empty);
						}
						else
							result_order = (d => d.Id);
					break;
					case "answer" : 
						if(is_where){
							result_where = (d=>d.Answer.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Answer);
					break;
					case "createby" : 
						if(is_where){
							result_where = (d=>d.CreateBy.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.CreateBy);
					break;
					case "createdate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _CreateDate))
								result_where = (d=>d.CreateDate == _CreateDate);
						}
						else
							result_order = (d => d.CreateDate);
					break;
					case "questionnaire" : 
						if(is_where){
							result_where = (d=>d.Questionnaire.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Questionnaire);
					break;
					case "section" : 
						if(is_where){
							result_where = (d=>d.Section.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Section);
					break;

                }
            }
            return (result_where, result_order);
        }
        #endregion
    }
}

