//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Tomori.Epartner.Data.Model;
using Vleko.Result;
using Tomori.Epartner.Core.Response;
using Tomori.Epartner.Core.Helper;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Caching.Memory;
using Tomori.Epartner.Core.Attributes;

namespace Tomori.Epartner.Core.DocumentTemplate.Query
{

    public class GetDocumentTemplateByteRequest : IRequest<ObjectResponse<FileByteObject>>
    {
        [Required]
        public string Code { get; set; }
    }
    internal class GetDocumentTemplateByteHandler : IRequestHandler<GetDocumentTemplateByteRequest, ObjectResponse<FileByteObject>>
    {
        private readonly ILogger _logger;
        private readonly IMediator _mediator;
        private readonly IGeneralHelper _helper;
        private readonly IMemoryCache _cache;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetDocumentTemplateByteHandler(
            ILogger<GetDocumentTemplateByteHandler> logger,
            IGeneralHelper helper,
            IMemoryCache cache,
            IMediator mediator,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _cache = cache;
            _helper = helper;
            _mediator = mediator;
            _context = context;
        }
        public async Task<ObjectResponse<FileByteObject>> Handle(GetDocumentTemplateByteRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<FileByteObject> result = new ObjectResponse<FileByteObject>();
            try
            {
                var item = await _context.Entity<Tomori.Epartner.Data.Model.Repository>().Where(d => d.Modul== CacheKey.DOCUMENT_TEMPLATE &&  d.Code.Trim().ToLower() == request.Code.Trim().ToLower() ).FirstOrDefaultAsync();
                if (item == null)
                {
                    result.NotFound($"Code Document {request.Code} Tidak Ditemukan");
                    return result;
                }
                result.Data = new FileByteObject()
                {
                    Filename = item.FileName,
                    MimeType = item.MimeType,
                    FIle = Convert.FromBase64String(item.Base64)
                };
                result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Download Document", request.Code);
                result.Error("Failed Download Document", ex.Message);
            }
            return result;
        }
    }
}

