//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using Tomori.Epartner.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Tomori.Epartner.Data.Model;

namespace Tomori.Epartner.Core.Response
{
    public partial class VendorSusunanSahamResponse: IMapResponse<VendorSusunanSahamResponse, Tomori.Epartner.Data.Model.VendorSusunanSaham>
    {
		public Guid Id{ get; set; }
		public string BadanUsaha{ get; set; }
		public int CivdId{ get; set; }
		public DateTime? CompletedDate{ get; set; }
		public string CreateBy{ get; set; }
		public DateTime CreateDate{ get; set; }
		public string DocNpwp{ get; set; }
		public string Email{ get; set; }
		public Guid? IdVendor{ get; set; }
		public decimal JumlahSaham{ get; set; }
		public string Nama{ get; set; }
		public string NoKtpKitas{ get; set; }
		public bool Perorangan{ get; set; }
		public string UpdateBy{ get; set; }
		public DateTime? UpdateDate{ get; set; }
		public string WargaNegara{ get; set; }


        public void Mapping(IMappingExpression<Tomori.Epartner.Data.Model.VendorSusunanSaham, VendorSusunanSahamResponse> map)
        {
            //use this for mapping
            //map.ForMember(d => d.object, opt => opt.MapFrom(s => s.EF_COLUMN));

        }
    }
}

