//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using Tomori.Epartner.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Tomori.Epartner.Data.Model;
using Vleko.Result;

namespace Tomori.Epartner.Core.Response
{
    public partial class RolePermissionResponse: IMapResponse<RolePermissionResponse, Tomori.Epartner.Data.Model.RolePermission>
    {
		public Guid Id{ get; set; }
		public ReferensiStringObject Role { get; set; }
        public PagePermissionResponse Permission { get; set; }
        public string CreateBy { get; set; }
        public DateTime CreateDate { get; set; }


        public void Mapping(IMappingExpression<Tomori.Epartner.Data.Model.RolePermission, RolePermissionResponse> map)
        {
            //use this for mapping
            map.ForMember(d => d.Permission, opt => opt.MapFrom(s => s.IdPermissionNavigation))
                .ForMember(d => d.Role, opt => opt.MapFrom(s => new ReferensiStringObject()
                {
                    Id = s.IdRole,
                    Nama = s.IdRoleNavigation.Name
                }));

        }
    }
}

