//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using Tomori.Epartner.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Tomori.Epartner.Data.Model;
using Tomori.Epartner.Core.Response;

namespace Tomori.Epartner.Core.Identity.Response
{
    public partial class UserDelegateResponse: IMapResponse<UserDelegateResponse, Tomori.Epartner.Data.Model.UserDelegate>
    {
		public Guid Id{ get; set; }
		public string CreateBy{ get; set; }
		public DateTime CreateDate{ get; set; }
		public DateTime ExpiredDate{ get; set; }
		public MiniUserResponse User { get; set; }
		public MiniUserResponse UserDelegasi { get; set; }
		public DateTime StartDate{ get; set; }


        public void Mapping(IMappingExpression<Tomori.Epartner.Data.Model.UserDelegate, UserDelegateResponse> map)
        {
            //use this for mapping
            map.ForMember(d => d.User, opt => opt.MapFrom(s => s.IdUserNavigation));
            map.ForMember(d => d.UserDelegasi, opt => opt.MapFrom(s => s.IdUserDelegateNavigation));

        }
    }
}

