//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Tomori.Epartner.Data;
using Tomori.Epartner.Data.Model;
using Vleko.Result;
using Tomori.Epartner.Core.Response;

namespace Tomori.Epartner.Core.VendorRekeningBank.Query
{

    public class GetVendorRekeningBankByIdRequest : IRequest<ObjectResponse<VendorRekeningBankResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetVendorRekeningBankByIdHandler : IRequestHandler<GetVendorRekeningBankByIdRequest, ObjectResponse<VendorRekeningBankResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetVendorRekeningBankByIdHandler(
            ILogger<GetVendorRekeningBankByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<VendorRekeningBankResponse>> Handle(GetVendorRekeningBankByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<VendorRekeningBankResponse> result = new ObjectResponse<VendorRekeningBankResponse>();
            try
            {
                var item = await _context.Entity<Tomori.Epartner.Data.Model.VendorRekeningBank>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<VendorRekeningBankResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id Tomori.Epartner.Data.Model.VendorRekeningBank {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail VendorRekeningBank", request.Id);
                result.Error("Failed Get Detail VendorRekeningBank", ex.Message);
            }
            return result;
        }
    }
}

