//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Tomori.Epartner.Core.Request
{
    public partial class ChangeConfigRequest
    {
		[Required]
		public bool Active{ get; set; }
		[Required]
		public string Field{ get; set; }
		[Required]
		public string Modul{ get; set; }

    }
}

